spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=java2_pro
    username: postgres
    password: xsk040525
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181